# fly.toml app configuration file generated for alchoi-com-astro on 2025-04-10T16:38:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alchoi-com-astro'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/dist/client/_astro'
  url_prefix = '/_astro'
